### ISSUE TITLE
complicate my peer life with a very complex js object structure

### ISSUE THREAD

**Issue by joelsrzalvarez** [b00tc4mp/isdi-bootcamp-202402#159]
```
const car = {
  color: "black",
  wheels: 3,
  engine: { 
      cylinders: 4, 
      size: 20
  },
  start: function() {
      console.log("Motor ...");
  },
  stop: function() {
      console.log("Motor ...");
  },
};
```
- [x] Cambiar el color del coche a Rojo
- [x] Súmale 1 rueda
- [x] Multiplica por 10 las cilindradas
- [x] El tamaño divídelo entre 5.
- [x] Cambia el estado del motor según este encendido o apagado

**Comment by Ireneroldan** [comment]
car.color = "red"; 

car.wheels = car.wheels + 1

car.engine.cylinders = car.engine.cylinders * 10

car.engine.size = car.engine.size / 5

start: function() {
        console.log("Motor encendido");
    },
    stop: function() {
        console.log("Motor apagado");
    },
